version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - "82:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      - redDocker
    volumes:
      - wordpress:/var/www/html
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: example
    networks:
      - redDocker
    volumes:
      - db:/var/lib/mysql
networks:
  redDocker:
volumes:
  wordpress:
  db:
