version: '3'
services:
  drupal:
    image: drupal:latest
    ports:
      - "81:80"
    volumes:
      - volumenDocker:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - volumenDocker:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root

volumes:
  volumenDocker: